apiVersion: v1
kind: Service
metadata:
  name: {{ include "desafio-twitter.fullname" . }}
  labels:
{{ include "desafio-twitter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "desafio-twitter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
