{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "desafio-twitter.serviceAccountName" . }}
  labels:
{{ include "desafio-twitter.labels" . | indent 4 }}
{{- end -}}
